name: Run all tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install

      - name: Test code
        run: mvn exec:exec@run-the-tests -Dexec.classpathScope=test
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}
          APPLITOOLS_SERVER_URL: https://eyesapi.applitools.com
          HEADLESS: true
